//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBooking.WPF.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EBooking.WPF.Properties.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Accommodation:.
        /// </summary>
        internal static string AccommodationDetails_DetailsForLabel {
            get {
                return ResourceManager.GetString("AccommodationDetails_DetailsForLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT RESERVATIONS.
        /// </summary>
        internal static string AccommodationDetails_ReservationsTabItemHeaderText {
            get {
                return ResourceManager.GetString("AccommodationDetails_ReservationsTabItemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return back.
        /// </summary>
        internal static string AccommodationDetails_ReturnButtonTooltip {
            get {
                return ResourceManager.GetString("AccommodationDetails_ReturnButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Details.
        /// </summary>
        internal static string AccommodationDetails_Title {
            get {
                return ResourceManager.GetString("AccommodationDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOMMODATION UNITS.
        /// </summary>
        internal static string AccommodationDetails_UnitsTabItemHeaderText {
            get {
                return ResourceManager.GetString("AccommodationDetails_UnitsTabItemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new accommodation.
        /// </summary>
        internal static string Accommodations_AddButtonTooltip {
            get {
                return ResourceManager.GetString("Accommodations_AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of units:.
        /// </summary>
        internal static string Accommodations_CardItemNumberOfUnitsLabel {
            get {
                return ResourceManager.GetString("Accommodations_CardItemNumberOfUnitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search accommodations.
        /// </summary>
        internal static string Accommodations_SearchButtonTooltip {
            get {
                return ResourceManager.GetString("Accommodations_SearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find accommodations....
        /// </summary>
        internal static string Accommodations_SearchFieldHelperText {
            get {
                return ResourceManager.GetString("Accommodations_SearchFieldHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Accommodations_SearchFieldHint {
            get {
                return ResourceManager.GetString("Accommodations_SearchFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Name.
        /// </summary>
        internal static string Accommodations_SubmitAddressFieldHint {
            get {
                return ResourceManager.GetString("Accommodations_SubmitAddressFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        internal static string Accommodations_SubmitLocationComboBoxHint {
            get {
                return ResourceManager.GetString("Accommodations_SubmitLocationComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Name.
        /// </summary>
        internal static string Accommodations_SubmitNameFieldHint {
            get {
                return ResourceManager.GetString("Accommodations_SubmitNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        internal static string Accommodations_SubmitTypeComboBoxHint {
            get {
                return ResourceManager.GetString("Accommodations_SubmitTypeComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodations.
        /// </summary>
        internal static string Accommodations_Title {
            get {
                return ResourceManager.GetString("Accommodations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Accommodation Unit.
        /// </summary>
        internal static string AccommodationUnits_AddButtonTooltip {
            get {
                return ResourceManager.GetString("AccommodationUnits_AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability period:.
        /// </summary>
        internal static string AccommodationUnits_CardItemAvailabilityPeriodLabel {
            get {
                return ResourceManager.GetString("AccommodationUnits_CardItemAvailabilityPeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of beds:.
        /// </summary>
        internal static string AccommodationUnits_CardItemNumberOfBedsLabel {
            get {
                return ResourceManager.GetString("AccommodationUnits_CardItemNumberOfBedsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per night:.
        /// </summary>
        internal static string AccommodationUnits_CardItemPricePerNightLabel {
            get {
                return ResourceManager.GetString("AccommodationUnits_CardItemPricePerNightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book here.
        /// </summary>
        internal static string AccommodationUnits_CardItemReserveButtonTooltip {
            get {
                return ResourceManager.GetString("AccommodationUnits_CardItemReserveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Features.
        /// </summary>
        internal static string AccommodationUnits_CardItemUnitFeaturesExpanderHeader {
            get {
                return ResourceManager.GetString("AccommodationUnits_CardItemUnitFeaturesExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no accommodation units to show.
        /// </summary>
        internal static string AccommodationUnits_NoUnitItemsLabel {
            get {
                return ResourceManager.GetString("AccommodationUnits_NoUnitItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available From.
        /// </summary>
        internal static string AccommodationUnits_SubmitAvailableFromDatePickerHint {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitAvailableFromDatePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available To.
        /// </summary>
        internal static string AccommodationUnits_SubmitAvailableToDatePickerHint {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitAvailableToDatePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Informations.
        /// </summary>
        internal static string AccommodationUnits_SubmitBasicInformationsTitle {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitBasicInformationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no features added.
        /// </summary>
        internal static string AccommodationUnits_SubmitNoFeaturesAddedLabel {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitNoFeaturesAddedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Beds.
        /// </summary>
        internal static string AccommodationUnits_SubmitNumberOfBedsFieldHint {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitNumberOfBedsFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Night.
        /// </summary>
        internal static string AccommodationUnits_SubmitPricePerNightFieldHint {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitPricePerNightFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add features to this unit....
        /// </summary>
        internal static string AccommodationUnits_SubmitSelectFeatureComboBoxHelperText {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitSelectFeatureComboBoxHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Feature.
        /// </summary>
        internal static string AccommodationUnits_SubmitSelectFeatureComboBoxHint {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitSelectFeatureComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Features.
        /// </summary>
        internal static string AccommodationUnits_SubmitUnitFeaturesTitle {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitUnitFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string AccommodationUnits_SubmitUnitNameFieldHint {
            get {
                return ResourceManager.GetString("AccommodationUnits_SubmitUnitNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATIONS.
        /// </summary>
        internal static string Codebook_LocationsTabItemHeaderText {
            get {
                return ResourceManager.GetString("Codebook_LocationsTabItemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage application coodebooks.
        /// </summary>
        internal static string Codebook_Subtitle {
            get {
                return ResourceManager.GetString("Codebook_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codebooks.
        /// </summary>
        internal static string Codebook_Title {
            get {
                return ResourceManager.GetString("Codebook_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT FEATURES.
        /// </summary>
        internal static string Codebook_UnitFeaturesTabItemHeaderText {
            get {
                return ResourceManager.GetString("Codebook_UnitFeaturesTabItemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string color_blue {
            get {
                return ResourceManager.GetString("color-blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string color_purple {
            get {
                return ResourceManager.GetString("color-purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string color_red {
            get {
                return ResourceManager.GetString("color-red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        internal static string color_teal {
            get {
                return ResourceManager.GetString("color-teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new flight.
        /// </summary>
        internal static string Flights_AddButtonTooltip {
            get {
                return ResourceManager.GetString("Flights_AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANDING.
        /// </summary>
        internal static string Flights_CardItemLandingLabel {
            get {
                return ResourceManager.GetString("Flights_CardItemLandingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAKE-OFF.
        /// </summary>
        internal static string Flights_CardItemTakeOffLabel {
            get {
                return ResourceManager.GetString("Flights_CardItemTakeOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket price:.
        /// </summary>
        internal static string Flights_CardItemTicketPriceLabel {
            get {
                return ResourceManager.GetString("Flights_CardItemTicketPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search flights.
        /// </summary>
        internal static string Flights_SearchButtonTooltip {
            get {
                return ResourceManager.GetString("Flights_SearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find flights....
        /// </summary>
        internal static string Flights_SearchFieldHelperText {
            get {
                return ResourceManager.GetString("Flights_SearchFieldHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Flights_SearchFieldHint {
            get {
                return ResourceManager.GetString("Flights_SearchFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date.
        /// </summary>
        internal static string Flights_SubmitArrivalDatePickerHint {
            get {
                return ResourceManager.GetString("Flights_SubmitArrivalDatePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Location.
        /// </summary>
        internal static string Flights_SubmitArrivalLocationComboBoxHint {
            get {
                return ResourceManager.GetString("Flights_SubmitArrivalLocationComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival time.
        /// </summary>
        internal static string Flights_SubmitArrivalTimePickerHint {
            get {
                return ResourceManager.GetString("Flights_SubmitArrivalTimePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avio Company Name.
        /// </summary>
        internal static string Flights_SubmitAvioCompanyNameFieldHint {
            get {
                return ResourceManager.GetString("Flights_SubmitAvioCompanyNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date.
        /// </summary>
        internal static string Flights_SubmitDepartureDatePickerHint {
            get {
                return ResourceManager.GetString("Flights_SubmitDepartureDatePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Location.
        /// </summary>
        internal static string Flights_SubmitDepartureLocationComboBoxHint {
            get {
                return ResourceManager.GetString("Flights_SubmitDepartureLocationComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time.
        /// </summary>
        internal static string Flights_SubmitDepartureTimePickerHint {
            get {
                return ResourceManager.GetString("Flights_SubmitDepartureTimePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Flight Class.
        /// </summary>
        internal static string Flights_SubmitFlightClassComboBoxHint {
            get {
                return ResourceManager.GetString("Flights_SubmitFlightClassComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Price.
        /// </summary>
        internal static string Flights_SubmitTicketPriceFieldHint {
            get {
                return ResourceManager.GetString("Flights_SubmitTicketPriceFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        internal static string Flights_Title {
            get {
                return ResourceManager.GetString("Flights_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Accommodation.
        /// </summary>
        internal static string GLOBAL_AccommodationAddDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added accommodation.
        /// </summary>
        internal static string GLOBAL_AccommodationAdded {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted accommodation.
        /// </summary>
        internal static string GLOBAL_AccommodationDeleted {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected accommodation?.
        /// </summary>
        internal static string GLOBAL_AccommodationDeleteDialogMessage {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Accommodation.
        /// </summary>
        internal static string GLOBAL_AccommodationEditDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Accommodation Unit.
        /// </summary>
        internal static string GLOBAL_AccommodationUnitAddDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationUnitAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added accommodation unit.
        /// </summary>
        internal static string GLOBAL_AccommodationUnitAdded {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationUnitAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted accommodation unit.
        /// </summary>
        internal static string GLOBAL_AccommodationUnitDeleted {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationUnitDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected accommodation unit?.
        /// </summary>
        internal static string GLOBAL_AccommodationUnitDeleteDialogMessage {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationUnitDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Accommodation Unit.
        /// </summary>
        internal static string GLOBAL_AccommodationUnitEditDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationUnitEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated accommodation unit.
        /// </summary>
        internal static string GLOBAL_AccommodationUnitUpdated {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationUnitUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated accommodation.
        /// </summary>
        internal static string GLOBAL_AccommodationUpdated {
            get {
                return ResourceManager.GetString("GLOBAL_AccommodationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string GLOBAL_DeleteButtonText {
            get {
                return ResourceManager.GetString("GLOBAL_DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string GLOBAL_DialogCancelButtonText {
            get {
                return ResourceManager.GetString("GLOBAL_DialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        internal static string GLOBAL_DialogCloseButtonText {
            get {
                return ResourceManager.GetString("GLOBAL_DialogCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string GLOBAL_DialogNoButtonText {
            get {
                return ResourceManager.GetString("GLOBAL_DialogNoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string GLOBAL_DialogOkButtonText {
            get {
                return ResourceManager.GetString("GLOBAL_DialogOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        internal static string GLOBAL_DialogSubmitButtonText {
            get {
                return ResourceManager.GetString("GLOBAL_DialogSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string GLOBAL_DialogYesButtonText {
            get {
                return ResourceManager.GetString("GLOBAL_DialogYesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        internal static string GLOBAL_EditButtonText {
            get {
                return ResourceManager.GetString("GLOBAL_EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Flight.
        /// </summary>
        internal static string GLOBAL_FlightAddDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_FlightAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected flight?.
        /// </summary>
        internal static string GLOBAL_FlightDeleteDialogMessage {
            get {
                return ResourceManager.GetString("GLOBAL_FlightDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Flight.
        /// </summary>
        internal static string GLOBAL_FlightEditDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_FlightEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future date is required.
        /// </summary>
        internal static string GLOBAL_FutureDateRequiredMessage {
            get {
                return ResourceManager.GetString("GLOBAL_FutureDateRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than or equal to departure date.
        /// </summary>
        internal static string GLOBAL_GreaterThanDepartureDateRequiredMessage {
            get {
                return ResourceManager.GetString("GLOBAL_GreaterThanDepartureDateRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than departure time.
        /// </summary>
        internal static string GLOBAL_GreaterThanDepartureTimeRequiredMessage {
            get {
                return ResourceManager.GetString("GLOBAL_GreaterThanDepartureTimeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than from date.
        /// </summary>
        internal static string GLOBAL_GreaterThanFromDateRequiredMessage {
            get {
                return ResourceManager.GetString("GLOBAL_GreaterThanFromDateRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string GLOBAL_InvalidLogin {
            get {
                return ResourceManager.GetString("GLOBAL_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change your password.
        /// </summary>
        internal static string GLOBAL_InvalidPasswordChange {
            get {
                return ResourceManager.GetString("GLOBAL_InvalidPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register account with entered data.
        /// </summary>
        internal static string GLOBAL_InvalidRegistration {
            get {
                return ResourceManager.GetString("GLOBAL_InvalidRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Location.
        /// </summary>
        internal static string GLOBAL_LocationAddDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_LocationAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected location?.
        /// </summary>
        internal static string GLOBAL_LocationDeleteDialogMessage {
            get {
                return ResourceManager.GetString("GLOBAL_LocationDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Location.
        /// </summary>
        internal static string GLOBAL_LocationEditDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_LocationEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can not be same as current one.
        /// </summary>
        internal static string GLOBAL_NotSameAsCurrentPasswordMessage {
            get {
                return ResourceManager.GetString("GLOBAL_NotSameAsCurrentPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please, try again.
        /// </summary>
        internal static string GLOBAL_PasswordMissmatch {
            get {
                return ResourceManager.GetString("GLOBAL_PasswordMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match.
        /// </summary>
        internal static string GLOBAL_PasswordsMustMatchMessage {
            get {
                return ResourceManager.GetString("GLOBAL_PasswordsMustMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive decimal number is required.
        /// </summary>
        internal static string GLOBAL_PositiveDecimalNumberRequiredMessage {
            get {
                return ResourceManager.GetString("GLOBAL_PositiveDecimalNumberRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive integer number is required.
        /// </summary>
        internal static string GLOBAL_PositiveIntegerNumberRequiredMessage {
            get {
                return ResourceManager.GetString("GLOBAL_PositiveIntegerNumberRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required*.
        /// </summary>
        internal static string GLOBAL_RequiredInputHint {
            get {
                return ResourceManager.GetString("GLOBAL_RequiredInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required!.
        /// </summary>
        internal static string GLOBAL_RequiredPropertyMessage {
            get {
                return ResourceManager.GetString("GLOBAL_RequiredPropertyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was successful!.
        /// </summary>
        internal static string GLOBAL_SuccessfulLogin {
            get {
                return ResourceManager.GetString("GLOBAL_SuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered your account!.
        /// </summary>
        internal static string GLOBAL_SuccessfulRegistration {
            get {
                return ResourceManager.GetString("GLOBAL_SuccessfulRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings changed successfully.
        /// </summary>
        internal static string GLOBAL_SuccessfulSettingsChange {
            get {
                return ResourceManager.GetString("GLOBAL_SuccessfulSettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information changed successfully.
        /// </summary>
        internal static string GLOBAL_SuccessfulUserInfoChange {
            get {
                return ResourceManager.GetString("GLOBAL_SuccessfulUserInfoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Trip Reservation.
        /// </summary>
        internal static string GLOBAL_TripReservationAddDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_TripReservationAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added trip reservation for.
        /// </summary>
        internal static string GLOBAL_TripReservationAdded {
            get {
                return ResourceManager.GetString("GLOBAL_TripReservationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted trip reservation for.
        /// </summary>
        internal static string GLOBAL_TripReservationDeleted {
            get {
                return ResourceManager.GetString("GLOBAL_TripReservationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected trip reservation?.
        /// </summary>
        internal static string GLOBAL_TripReservationDeleteDialogMessage {
            get {
                return ResourceManager.GetString("GLOBAL_TripReservationDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trip Reservation.
        /// </summary>
        internal static string GLOBAL_TripReservationEditDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_TripReservationEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated trip reservation for.
        /// </summary>
        internal static string GLOBAL_TripReservationUpdated {
            get {
                return ResourceManager.GetString("GLOBAL_TripReservationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Unit Feature.
        /// </summary>
        internal static string GLOBAL_UnitFeatureAddDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_UnitFeatureAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected unit feature?.
        /// </summary>
        internal static string GLOBAL_UnitFeatureDeleteDialogMessage {
            get {
                return ResourceManager.GetString("GLOBAL_UnitFeatureDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Unit Feature.
        /// </summary>
        internal static string GLOBAL_UnitFeatureEditDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_UnitFeatureEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Accommodation Unit Reservation.
        /// </summary>
        internal static string GLOBAL_UnitReservationAddDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_UnitReservationAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added unit reservation for.
        /// </summary>
        internal static string GLOBAL_UnitReservationAdded {
            get {
                return ResourceManager.GetString("GLOBAL_UnitReservationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted unit reservation for.
        /// </summary>
        internal static string GLOBAL_UnitReservationDeleted {
            get {
                return ResourceManager.GetString("GLOBAL_UnitReservationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected unit reservation?.
        /// </summary>
        internal static string GLOBAL_UnitReservationDeleteDialogMessage {
            get {
                return ResourceManager.GetString("GLOBAL_UnitReservationDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Accommodation Unit Reservation.
        /// </summary>
        internal static string GLOBAL_UnitReservationEditDialogTitle {
            get {
                return ResourceManager.GetString("GLOBAL_UnitReservationEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated unit reservation for.
        /// </summary>
        internal static string GLOBAL_UnitReservationUpdated {
            get {
                return ResourceManager.GetString("GLOBAL_UnitReservationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken.
        /// </summary>
        internal static string GLOBAL_UsernameTaken {
            get {
                return ResourceManager.GetString("GLOBAL_UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back!.
        /// </summary>
        internal static string GLOBAL_WelcomeMessage {
            get {
                return ResourceManager.GetString("GLOBAL_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...Or.
        /// </summary>
        internal static string Landing_LoginDiscoveryLabel {
            get {
                return ResourceManager.GetString("Landing_LoginDiscoveryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string Landing_LoginLinkText {
            get {
                return ResourceManager.GetString("Landing_LoginLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to read application manual.
        /// </summary>
        internal static string Landing_ReadDocumentationLinkText {
            get {
                return ResourceManager.GetString("Landing_ReadDocumentationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you new here?.
        /// </summary>
        internal static string Landing_RegisterDiscoveryLabel {
            get {
                return ResourceManager.GetString("Landing_RegisterDiscoveryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string Landing_RegisterLinkText {
            get {
                return ResourceManager.GetString("Landing_RegisterLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to &quot;E-Booking&quot;.
        /// </summary>
        internal static string Landing_WelcomeTitle {
            get {
                return ResourceManager.GetString("Landing_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new location.
        /// </summary>
        internal static string Locations_AddButtonTooltip {
            get {
                return ResourceManager.GetString("Locations_AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected locations.
        /// </summary>
        internal static string Locations_DeleteSelectedButtonTooltip {
            get {
                return ResourceManager.GetString("Locations_DeleteSelectedButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Locations_GridColumnHeaderActionLabel {
            get {
                return ResourceManager.GetString("Locations_GridColumnHeaderActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Locations_GridColumnHeaderCityLabel {
            get {
                return ResourceManager.GetString("Locations_GridColumnHeaderCityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Locations_GridColumnHeaderCountryLabel {
            get {
                return ResourceManager.GetString("Locations_GridColumnHeaderCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no locations to show.
        /// </summary>
        internal static string Locations_NoItemsToShowLabel {
            get {
                return ResourceManager.GetString("Locations_NoItemsToShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search locations.
        /// </summary>
        internal static string Locations_SearchButtonTooltip {
            get {
                return ResourceManager.GetString("Locations_SearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find locations....
        /// </summary>
        internal static string Locations_SearchFieldHelperText {
            get {
                return ResourceManager.GetString("Locations_SearchFieldHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Locations_SearchFieldHint {
            get {
                return ResourceManager.GetString("Locations_SearchFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        internal static string Locations_SubmitCityNameFieldHint {
            get {
                return ResourceManager.GetString("Locations_SubmitCityNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        internal static string Locations_SubmitCountryNameFieldHint {
            get {
                return ResourceManager.GetString("Locations_SubmitCountryNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations codebook....
        /// </summary>
        internal static string Locations_Title {
            get {
                return ResourceManager.GetString("Locations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_LoginButtonText {
            get {
                return ResourceManager.GetString("Login_LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_PasswordFieldPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Login_RegisterButtonText {
            get {
                return ResourceManager.GetString("Login_RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, login to start using this system .
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_UsernameFieldPlaceholder {
            get {
                return ResourceManager.GetString("Login_UsernameFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit application?.
        /// </summary>
        internal static string Main_ConfirmExitDialogMessage {
            get {
                return ResourceManager.GetString("Main_ConfirmExitDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        internal static string Main_ExitButtonText {
            get {
                return ResourceManager.GetString("Main_ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to landing page.
        /// </summary>
        internal static string Main_HomePageButtonTooltip {
            get {
                return ResourceManager.GetString("Main_HomePageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out....
        /// </summary>
        internal static string Main_LogoutButtonTooltip {
            get {
                return ResourceManager.GetString("Main_LogoutButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open main menu.
        /// </summary>
        internal static string Main_MenuButtonTooltip {
            get {
                return ResourceManager.GetString("Main_MenuButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book your next trip or accommodation with E-Booking.
        /// </summary>
        internal static string Main_SloganText {
            get {
                return ResourceManager.GetString("Main_SloganText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Main_ThemeDarkText {
            get {
                return ResourceManager.GetString("Main_ThemeDarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Main_ThemeLightText {
            get {
                return ResourceManager.GetString("Main_ThemeLightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Main_ThemeSelectorText {
            get {
                return ResourceManager.GetString("Main_ThemeSelectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodations.
        /// </summary>
        internal static string Menu_AccommodationsTitle {
            get {
                return ResourceManager.GetString("Menu_AccommodationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codebooks.
        /// </summary>
        internal static string Menu_CodebookTitle {
            get {
                return ResourceManager.GetString("Menu_CodebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        internal static string Menu_FlightsTitle {
            get {
                return ResourceManager.GetString("Menu_FlightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Menu_LoginTitle {
            get {
                return ResourceManager.GetString("Menu_LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Menu_RegisterTitle {
            get {
                return ResourceManager.GetString("Menu_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        internal static string Menu_ReservationsTitle {
            get {
                return ResourceManager.GetString("Menu_ReservationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_SettingsTitle {
            get {
                return ResourceManager.GetString("Menu_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN MENU.
        /// </summary>
        internal static string Menu_TitleText {
            get {
                return ResourceManager.GetString("Menu_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Administrator.
        /// </summary>
        internal static string Register_AdminTabItemHeaderText {
            get {
                return ResourceManager.GetString("Register_AdminTabItemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string Register_DisplayNameFieldPlaceholder {
            get {
                return ResourceManager.GetString("Register_DisplayNameFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Employee.
        /// </summary>
        internal static string Register_EmployeeTabItemHeaderText {
            get {
                return ResourceManager.GetString("Register_EmployeeTabItemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Register_FirstNameFieldPlaceholder {
            get {
                return ResourceManager.GetString("Register_FirstNameFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Register_LastNameFieldPlaceholder {
            get {
                return ResourceManager.GetString("Register_LastNameFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Register_PasswordFieldPlaceholder {
            get {
                return ResourceManager.GetString("Register_PasswordFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string Register_RegisterButtonText {
            get {
                return ResourceManager.GetString("Register_RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        internal static string Register_RepeatPasswordFieldPlaceholder {
            get {
                return ResourceManager.GetString("Register_RepeatPasswordFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string Register_Subtitle {
            get {
                return ResourceManager.GetString("Register_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Register_UsernameFieldPlaceholder {
            get {
                return ResourceManager.GetString("Register_UsernameFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Reservations.
        /// </summary>
        internal static string Reservations_TripReservationsTitle {
            get {
                return ResourceManager.GetString("Reservations_TripReservationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIP RESERVATIONS.
        /// </summary>
        internal static string Reservations_TripsTabItemHeaderText {
            get {
                return ResourceManager.GetString("Reservations_TripsTabItemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Units Reservations.
        /// </summary>
        internal static string Reservations_UnitReservationsTitle {
            get {
                return ResourceManager.GetString("Reservations_UnitReservationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT RESERVATIONS.
        /// </summary>
        internal static string Reservations_UnitsTabItemHeaderText {
            get {
                return ResourceManager.GetString("Reservations_UnitsTabItemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE USER INFORMATIONS.
        /// </summary>
        internal static string Settings_ChangeInfoButtonText {
            get {
                return ResourceManager.GetString("Settings_ChangeInfoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PASSWORD.
        /// </summary>
        internal static string Settings_ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("Settings_ChangePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string Settings_ChangePasswordCurrentPasswordFieldHint {
            get {
                return ResourceManager.GetString("Settings_ChangePasswordCurrentPasswordFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string Settings_ChangePasswordNewPasswordFieldHint {
            get {
                return ResourceManager.GetString("Settings_ChangePasswordNewPasswordFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat New Password.
        /// </summary>
        internal static string Settings_ChangePasswordRepeatNewPasswordFieldHint {
            get {
                return ResourceManager.GetString("Settings_ChangePasswordRepeatNewPasswordFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        internal static string Settings_ChangePasswordTitle {
            get {
                return ResourceManager.GetString("Settings_ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string Settings_ChangeUserInfoAdminNameFieldHint {
            get {
                return ResourceManager.GetString("Settings_ChangeUserInfoAdminNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Settings_ChangeUserInfoEmployeeFirstNameFieldHint {
            get {
                return ResourceManager.GetString("Settings_ChangeUserInfoEmployeeFirstNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Settings_ChangeUserInfoEmployeeLastNameFieldHint {
            get {
                return ResourceManager.GetString("Settings_ChangeUserInfoEmployeeLastNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Settings_ChangeUserInfoPasswordFieldHint {
            get {
                return ResourceManager.GetString("Settings_ChangeUserInfoPasswordFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Informations.
        /// </summary>
        internal static string Settings_ChangeUserInfoTitle {
            get {
                return ResourceManager.GetString("Settings_ChangeUserInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Settings_ChangeUserInfoUsernameFieldHint {
            get {
                return ResourceManager.GetString("Settings_ChangeUserInfoUsernameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Settings_DisplayNameLabel {
            get {
                return ResourceManager.GetString("Settings_DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string Settings_FirstNameLabel {
            get {
                return ResourceManager.GetString("Settings_FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Informations.
        /// </summary>
        internal static string Settings_InfoTitle {
            get {
                return ResourceManager.GetString("Settings_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string Settings_LastNameLabel {
            get {
                return ResourceManager.GetString("Settings_LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Look and Feel.
        /// </summary>
        internal static string Settings_LookAndFeelTitle {
            get {
                return ResourceManager.GetString("Settings_LookAndFeelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Changes.
        /// </summary>
        internal static string Settings_RevertChangesButtonText {
            get {
                return ResourceManager.GetString("Settings_RevertChangesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string Settings_SaveChangesButtonText {
            get {
                return ResourceManager.GetString("Settings_SaveChangesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, save your settings changes before leaving..
        /// </summary>
        internal static string Settings_SaveSettingsDialogMessage {
            get {
                return ResourceManager.GetString("Settings_SaveSettingsDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save is required*.
        /// </summary>
        internal static string Settings_SaveSettingsReminderText {
            get {
                return ResourceManager.GetString("Settings_SaveSettingsReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Display Language.
        /// </summary>
        internal static string Settings_SelectLanguageLabel {
            get {
                return ResourceManager.GetString("Settings_SelectLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Primary Color.
        /// </summary>
        internal static string Settings_SelectPrimaryColorLabel {
            get {
                return ResourceManager.GetString("Settings_SelectPrimaryColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Secondary Color.
        /// </summary>
        internal static string Settings_SelectSecondaryColorLabel {
            get {
                return ResourceManager.GetString("Settings_SelectSecondaryColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account informations or customize application look and feel.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Settings_UsernameLabel {
            get {
                return ResourceManager.GetString("Settings_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian Cyrilic.
        /// </summary>
        internal static string sr_Cyrl {
            get {
                return ResourceManager.GetString("sr-Cyrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian Latin.
        /// </summary>
        internal static string sr_Latn {
            get {
                return ResourceManager.GetString("sr-Latn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Seats:.
        /// </summary>
        internal static string TripReservation_DetailsNumberOfSeatsLabel {
            get {
                return ResourceManager.GetString("TripReservation_DetailsNumberOfSeatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation On Name:.
        /// </summary>
        internal static string TripReservation_DetailsReservationOnNameLabel {
            get {
                return ResourceManager.GetString("TripReservation_DetailsReservationOnNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved By:.
        /// </summary>
        internal static string TripReservation_DetailsReservedByLabel {
            get {
                return ResourceManager.GetString("TripReservation_DetailsReservedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Reservation Details.
        /// </summary>
        internal static string TripReservation_DetailsTitle {
            get {
                return ResourceManager.GetString("TripReservation_DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price:.
        /// </summary>
        internal static string TripReservation_DetailsTotalPriceLabel {
            get {
                return ResourceManager.GetString("TripReservation_DetailsTotalPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Type:.
        /// </summary>
        internal static string TripReservation_DetailsTripTypeLabel {
            get {
                return ResourceManager.GetString("TripReservation_DetailsTripTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight list.
        /// </summary>
        internal static string TripReservation_FlightsListExpanderHeaderText {
            get {
                return ResourceManager.GetString("TripReservation_FlightsListExpanderHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no flights added....
        /// </summary>
        internal static string TripReservation_FlightsListExpanderNoItemsLabel {
            get {
                return ResourceManager.GetString("TripReservation_FlightsListExpanderNoItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new trip reservation.
        /// </summary>
        internal static string TripReservations_AddButtonTooltip {
            get {
                return ResourceManager.GetString("TripReservations_AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected trip reservations.
        /// </summary>
        internal static string TripReservations_DeleteSelectedButtonTooltip {
            get {
                return ResourceManager.GetString("TripReservations_DeleteSelectedButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string TripReservations_GridColumnHeaderActionLabel {
            get {
                return ResourceManager.GetString("TripReservations_GridColumnHeaderActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Seats.
        /// </summary>
        internal static string TripReservations_GridColumnHeaderNumberOfSeatsLabel {
            get {
                return ResourceManager.GetString("TripReservations_GridColumnHeaderNumberOfSeatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation On Name.
        /// </summary>
        internal static string TripReservations_GridColumnHeaderReservationOnNameLabel {
            get {
                return ResourceManager.GetString("TripReservations_GridColumnHeaderReservationOnNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved By.
        /// </summary>
        internal static string TripReservations_GridColumnHeaderReservedByLabel {
            get {
                return ResourceManager.GetString("TripReservations_GridColumnHeaderReservedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string TripReservations_GridColumnHeaderTotalPriceLabel {
            get {
                return ResourceManager.GetString("TripReservations_GridColumnHeaderTotalPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Summary.
        /// </summary>
        internal static string TripReservations_GridColumnHeaderTripSummaryLabel {
            get {
                return ResourceManager.GetString("TripReservations_GridColumnHeaderTripSummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Type.
        /// </summary>
        internal static string TripReservations_GridColumnHeaderTripTypeLabel {
            get {
                return ResourceManager.GetString("TripReservations_GridColumnHeaderTripTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no trip reservations to show.
        /// </summary>
        internal static string TripReservations_NoItemsToShowLabel {
            get {
                return ResourceManager.GetString("TripReservations_NoItemsToShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search trip reservations.
        /// </summary>
        internal static string TripReservations_SearchButtonTooltip {
            get {
                return ResourceManager.GetString("TripReservations_SearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find trip reservations....
        /// </summary>
        internal static string TripReservations_SearchFieldHelperText {
            get {
                return ResourceManager.GetString("TripReservations_SearchFieldHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string TripReservations_SearchFieldHint {
            get {
                return ResourceManager.GetString("TripReservations_SearchFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Informations.
        /// </summary>
        internal static string TripReservations_SubmitBasicInformationsTitle {
            get {
                return ResourceManager.GetString("TripReservations_SubmitBasicInformationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        internal static string TripReservations_SubmitFlightsTitle {
            get {
                return ResourceManager.GetString("TripReservations_SubmitFlightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Seats.
        /// </summary>
        internal static string TripReservations_SubmitNumberOfSeatsFieldHint {
            get {
                return ResourceManager.GetString("TripReservations_SubmitNumberOfSeatsFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation On Name.
        /// </summary>
        internal static string TripReservations_SubmitReservationOnNameFieldHint {
            get {
                return ResourceManager.GetString("TripReservations_SubmitReservationOnNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to fliter flights that are dispalyed....
        /// </summary>
        internal static string TripReservations_SubmitSelectFlightDatePickerHelperText {
            get {
                return ResourceManager.GetString("TripReservations_SubmitSelectFlightDatePickerHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Flight Date.
        /// </summary>
        internal static string TripReservations_SubmitSelectFlightDatePickerHint {
            get {
                return ResourceManager.GetString("TripReservations_SubmitSelectFlightDatePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add flight to this trip....
        /// </summary>
        internal static string TripReservations_SubmitSelectFlightToAddComboBoxHelperText {
            get {
                return ResourceManager.GetString("TripReservations_SubmitSelectFlightToAddComboBoxHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Flight.
        /// </summary>
        internal static string TripReservations_SubmitSelectFlightToAddComboBoxHint {
            get {
                return ResourceManager.GetString("TripReservations_SubmitSelectFlightToAddComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Type.
        /// </summary>
        internal static string TripReservations_SubmitSelectTypeComboBoxHint {
            get {
                return ResourceManager.GetString("TripReservations_SubmitSelectTypeComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price:.
        /// </summary>
        internal static string TripReservations_SubmitTotalPriceLabel {
            get {
                return ResourceManager.GetString("TripReservations_SubmitTotalPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new unit feature.
        /// </summary>
        internal static string UnitFeatures_AddButtonTooltip {
            get {
                return ResourceManager.GetString("UnitFeatures_AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected unit features.
        /// </summary>
        internal static string UnitFeatures_DeleteSelectedButtonTooltip {
            get {
                return ResourceManager.GetString("UnitFeatures_DeleteSelectedButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string UnitFeatures_GridColumnHeaderActionLabel {
            get {
                return ResourceManager.GetString("UnitFeatures_GridColumnHeaderActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Name.
        /// </summary>
        internal static string UnitFeatures_GridColumnHeaderFeatureNameLabel {
            get {
                return ResourceManager.GetString("UnitFeatures_GridColumnHeaderFeatureNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no unit features to show.
        /// </summary>
        internal static string UnitFeatures_NoItemsToShowLabel {
            get {
                return ResourceManager.GetString("UnitFeatures_NoItemsToShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search unit features.
        /// </summary>
        internal static string UnitFeatures_SearchButtonTooltip {
            get {
                return ResourceManager.GetString("UnitFeatures_SearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find accommodation unit features....
        /// </summary>
        internal static string UnitFeatures_SearchFieldHelperText {
            get {
                return ResourceManager.GetString("UnitFeatures_SearchFieldHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string UnitFeatures_SearchFieldHint {
            get {
                return ResourceManager.GetString("UnitFeatures_SearchFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Name.
        /// </summary>
        internal static string UnitFeatures_SubmitFeatureNameFieldHint {
            get {
                return ResourceManager.GetString("UnitFeatures_SubmitFeatureNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Unit Features Codebook....
        /// </summary>
        internal static string UnitFeatures_Title {
            get {
                return ResourceManager.GetString("UnitFeatures_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected unit reservations.
        /// </summary>
        internal static string UnitReservations_DeleteSelectedButtonTooltip {
            get {
                return ResourceManager.GetString("UnitReservations_DeleteSelectedButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string UnitReservations_GridColumnHeaderActionLabel {
            get {
                return ResourceManager.GetString("UnitReservations_GridColumnHeaderActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of People.
        /// </summary>
        internal static string UnitReservations_GridColumnHeaderNumberOfPeopleLabel {
            get {
                return ResourceManager.GetString("UnitReservations_GridColumnHeaderNumberOfPeopleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved From.
        /// </summary>
        internal static string UnitReservations_GridColumnHeaderReservationFromLabel {
            get {
                return ResourceManager.GetString("UnitReservations_GridColumnHeaderReservationFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation On Name.
        /// </summary>
        internal static string UnitReservations_GridColumnHeaderReservationOnNameLabel {
            get {
                return ResourceManager.GetString("UnitReservations_GridColumnHeaderReservationOnNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved To.
        /// </summary>
        internal static string UnitReservations_GridColumnHeaderReservationToLabel {
            get {
                return ResourceManager.GetString("UnitReservations_GridColumnHeaderReservationToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved By.
        /// </summary>
        internal static string UnitReservations_GridColumnHeaderReservedByLabel {
            get {
                return ResourceManager.GetString("UnitReservations_GridColumnHeaderReservedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string UnitReservations_GridColumnHeaderTotalPriceLabel {
            get {
                return ResourceManager.GetString("UnitReservations_GridColumnHeaderTotalPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string UnitReservations_GridColumnHeaderUnitNameLabel {
            get {
                return ResourceManager.GetString("UnitReservations_GridColumnHeaderUnitNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no unit reservations to show.
        /// </summary>
        internal static string UnitReservations_NoItemsToShowLabel {
            get {
                return ResourceManager.GetString("UnitReservations_NoItemsToShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search unit reservations.
        /// </summary>
        internal static string UnitReservations_SearchButtonTooltip {
            get {
                return ResourceManager.GetString("UnitReservations_SearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find unit reservations....
        /// </summary>
        internal static string UnitReservations_SearchFieldHelperText {
            get {
                return ResourceManager.GetString("UnitReservations_SearchFieldHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string UnitReservations_SearchFieldHint {
            get {
                return ResourceManager.GetString("UnitReservations_SearchFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Adults.
        /// </summary>
        internal static string UnitReservations_SubmitNumberOfAdultsFieldHint {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitNumberOfAdultsFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Children.
        /// </summary>
        internal static string UnitReservations_SubmitNumberOfChildrenFieldHint {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitNumberOfChildrenFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price Per Night:.
        /// </summary>
        internal static string UnitReservations_SubmitPricePerNightLabel {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitPricePerNightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation From.
        /// </summary>
        internal static string UnitReservations_SubmitReservationFromDatePickerHint {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitReservationFromDatePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation On Name.
        /// </summary>
        internal static string UnitReservations_SubmitReservationOnNameFieldHint {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitReservationOnNameFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation To.
        /// </summary>
        internal static string UnitReservations_SubmitReservationToDatePickerHint {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitReservationToDatePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price:.
        /// </summary>
        internal static string UnitReservations_SubmitTotalPriceLabel {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitTotalPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Period:.
        /// </summary>
        internal static string UnitReservations_SubmitUnitAvailabilityLabel {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitUnitAvailabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Unit Name:.
        /// </summary>
        internal static string UnitReservations_SubmitUnitNameLabel {
            get {
                return ResourceManager.GetString("UnitReservations_SubmitUnitNameLabel", resourceCulture);
            }
        }
    }
}
